define([], function() {
  return {
    "PropertyPaneDescription": "Configure where the HTML content is stored in SharePoint.",
    "ContentGroupName": "HTML source",
    "BrowseGroupName": "Browse SharePoint",
    "ManualEntryGroupName": "Or enter manually",
    "FolderPickerLabel": "Content folder",
    "FilePickerLabel": "HTML file",
    "FilePickerButtonLabel": "Select HTML file",
    "SharePointLocationFieldLabel": "SharePoint location",
    "SharePointLocationFieldDescription": "Site-relative folder (e.g. SiteAssets/html-app) or server-relative path (e.g. /sites/demo/Shared Documents/html-app).",
    "InitialFileFieldLabel": "Initial file",
    "InitialFileFieldDescription": "File name to load when the web part opens (e.g. index.html).",
    "MissingLocationMessage": "Configure the SharePoint location in the web part properties.",
    "LoadErrorMessage": "Unable to build a URL for the configured HTML file.",
    "SharePointLocationRequired": "SharePoint location is required.",
    "SharePointLocationInvalidPath": "Location cannot contain '..' or backslashes.",
    "SharePointLocationInvalidUrl": "Absolute URLs must be valid http or https addresses.",
    "InitialFileRequired": "Initial file is required.",
    "InitialFileInvalid": "Enter a file name only (e.g. index.html), without folder paths.",
    "LoadingMessage": "Loading HTML content…",
    "LoadTimeoutMessage": "The HTML file is taking too long to load. Check the path, permissions, and that the file exists.",
    "LoadFailedMessage": "The HTML file could not be loaded. Verify the SharePoint location and file name.",
    "RetryButtonLabel": "Retry",
    "SecurityGroupName": "Security",
    "AllowedHostsFieldLabel": "Allowed hosts",
    "AllowedHostsFieldDescription": "Comma-separated host names permitted for HTML content. The current site host is always included (e.g. contoso.sharepoint.com).",
    "AllowedHostsInvalid": "Enter valid host names separated by commas.",
    "RestrictToCurrentSiteLabel": "Restrict to current site collection",
    "RestrictToCurrentSiteOnText": "On",
    "RestrictToCurrentSiteOffText": "Off",
    "UrlNotAllowedMessage": "The configured HTML URL is not allowed by this web part's security settings."
  }
});
